#!/usr/bin/env bash

OS=$(uname -s)
case "${OS}" in
    Darwin)
        ;;
    Linux)
        ;;
    *)
        echo "Unsupported system: ${OS}" >&2
        exit 1
        ;;
esac

export HOTATE=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)

# load color utilities
source "${HOTATE}/lib/style.core.bash"


# load theme
source "${HOTATE}/lib/base.theme.bash"
if [ -z "$HOTATE_THEME" ]; then
    export HOTATE_THEME="minimal"
fi
source "${HOTATE}/lib/${HOTATE_THEME}.theme.bash"

for file_type in "plugin" "alias" "completion"
do
    LIB="${HOTATE}/lib/*.${file_type}.bash"
    for bash_file in $LIB
    do
        source $bash_file
    done
done

